//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Messages
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> SentDate { get; set; }
        public Nullable<int> FromUserId { get; set; }
        public Nullable<int> ToUserId { get; set; }
        public string Subject { get; set; }
        public string Message { get; set; }
        public Nullable<bool> FromHighlighted { get; set; }
        public Nullable<bool> ToHighlighted { get; set; }
        public Nullable<bool> FromDeleted { get; set; }
        public Nullable<bool> ToDeleted { get; set; }
        public Nullable<bool> FromDeletedPerm { get; set; }
        public Nullable<bool> ToDeletedPerm { get; set; }
        public Nullable<bool> Read { get; set; }
    
        public virtual Users Users { get; set; }
        public virtual Users Users1 { get; set; }
    }
}
